# -----------------------------------------------------------------------------
# apk dependencies
# -----------------------------------------------------------------------------
FROM node:9.7.0-alpine as apk-dependencies
WORKDIR /app

# Install system dependencies.
RUN apk add --update --no-cache --virtual .apk git python make g++

# -----------------------------------------------------------------------------
# npm dependencies
# -----------------------------------------------------------------------------
FROM apk-dependencies as npm-dependencies

# Copy whole workspace into the container. This seems crazy but
# is actually more efficient than copying each package.json
# individually.
COPY . /app

# Install node dependencies and clean up afterwards.
RUN yarn install --ignore-engines --frozen-lockfile --pure-lockfile --production && \
  cp -R node_modules node_modules_production && \
  yarn install --ignore-engines --frozen-lockfile --pure-lockfile && \
  yarn cache clean && \
  apk del .apk

# -----------------------------------------------------------------------------
# base development image
# -----------------------------------------------------------------------------
FROM node:9.7.0-alpine as node-development
COPY --from=npm-dependencies /app/node_modules /app/node_modules
COPY package.json yarn.lock /app/

# -----------------------------------------------------------------------------
# base production image
# -----------------------------------------------------------------------------
FROM node:9.7.0-alpine as node-production
COPY --from=npm-dependencies /app/node_modules_production /app/node_modules
COPY package.json yarn.lock /app/
